# Linear Regression 

In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))
x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([ 21.41658255, -28.91621057,  23.19497439, -48.28355927,
        -0.86508364,   1.80477639,   5.17018001, -22.22094212,
       -42.20656957,  13.96127771, -42.20343146,  -4.01360574,
        13.51987918, -10.33182704,   5.1191233 , -44.44979534,
         1.48747489,   5.39611761, -38.00439638, -46.3005982 ,
       -46.75943569,  -6.37078071,  27.42628747, -16.32271557,
       -44.77719396, -10.48733575,   1.84691042, -52.45241257,
       -50.38162247,   5.15701152, -24.16851932, -42.0974381 ,
       -22.36420534, -12.07797568,   7.78735665,  -8.48993519,
       -52.82237837, -10.60062822, -30.15770791, -40.7285182 ,
       -12.10527547, -10.50237651,   7.57553766, -48.14001032,
        -8.53008639, -12.44719443,   9.97025991, -18.250977  ,
         9.31164076, -20.97317167])

In [5]:
x1

array([19,  4, 18,  6,  8,  5,  5, 19,  1,  9, 13,  2,  9, 19, 19,  4, 11,
        9, 15,  1,  9,  1, 16, 12, 10, 11,  5,  4,  7, 15,  4,  5,  7, 12,
       12, 16,  8, 13, 11, 12,  6, 13, 16, 10, 14, 18, 11, 15, 11, 10])

In [6]:
x2

array([ 5, 10,  4, 16,  5,  3,  2, 16, 12,  2, 18,  3,  2, 13,  9, 14,  6,
        4, 18, 13, 17,  3,  2, 11, 17,  9,  3, 16, 17,  7,  9, 14, 10, 10,
        5, 11, 18, 10, 14, 17,  7, 10,  7, 18, 10, 13,  4, 13,  4, 11])

In [7]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})
w=np.zeros(x.shape[1])

In [8]:
def myprediction(features,weights):
    predictions=np.dot(features,weights)
    return(predictions)

#myprediction(x,w)

In [9]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [10]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

#mycost(y,x,w)

In [11]:
def gradient(target,features,weights):
    error=myerror(target,features,weights)
    gradient=-np.dot(features.T,error)
    return(gradient)

#gradient(y,x,w)

## Manual Implementation

In [12]:
def my_lr(target,features,learning_rate):
    weights=np.zeros(features.shape[1])
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn
        if i%10000==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.000001)

37073.52188201714 [-0.00837405 -0.00559442 -0.01286195]
34.45467956141961 [ 1.41483776  2.09177058 -3.90342762]
11.899546780590814 [ 2.48700625  2.04259532 -3.94843108]
5.820913942077615 [ 3.04360622  2.01706115 -3.97178819]
4.182715753670493 [ 3.33255672  2.00380547 -3.98391368]
3.7412195528311525 [ 3.48256102  1.99692398 -3.99020844]
3.622235844550373 [ 3.5604335   1.99335156 -3.99347628]
3.590169605227545 [ 3.60085982  1.99149699 -3.99517272]
3.581527718710726 [ 3.62184654  1.99053422 -3.99605341]
3.5791987208567226 [ 3.63274147  1.99003441 -3.9965106 ]


array([ 3.63839702,  1.98977496, -3.99674793])

## Sklearn

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr=LinearRegression()

In [15]:
x.shape

(50, 3)

In [16]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
lr.coef_

array([ 1.98949482, -3.99700418])

In [18]:
lr.intercept_

3.6445034912153798